#!/bin/bash

#remove old apt.dat
rm apt.dat

#write header of file into apt.dat
echo "I">>apt.dat
echo "1000 Generated by WorldEditor">>apt.dat

for FILENAME in *.dat; do
    
    if [ "$FILENAME" != "apt.dat" ];
    then
        while read line; do
            if [[ "$line" != I* && "$line" != 1000* && "$line" != 99* ]];
            then
                echo "$line">>apt.dat
            fi
            
        done < $FILENAME
    fi

done

echo "99">>apt.dat

